### ISSUE TITLE
Alfie error at Phylip Step running test

### ISSUE THREAD

**Issue by jpummil** [igorrcosta/alfie#4]
Believe I have it all set up properly, but when I run the test as shown, it fails at the phylip step:

python alfie.py -v -r test/homo_y.fasta -i test/pan_y.fasta -g test/y.gtf
starting al_finder
running makeblastdb for genome: test/homo_y.fasta
running makeblastdb for genome: test/pan_y.fasta
starting blast
Blasting query: 1/1 against db /home/jpummil/Applications/alfie-master/out/0.db
Blasting query: 1/1 against db /home/jpummil/Applications/alfie-master/out/1.db
starting alignment
Traceback (most recent call last):
  File "/home/jpummil/Applications/alfie-master/alfie.py", line 168, in <module>
    main()
  File "/home/jpummil/Applications/alfie-master/alfie.py", line 153, in main
    al_align.main(align_args)
  File "/home/jpummil/Applications/alfie-master/al_align.py", line 315, in main
    make_phylip(align_folder, phylip_folder, nexus_files)
  File "/home/jpummil/Applications/alfie-master/al_align.py", line 609, in make_phylip
    seq = fasta2phylip(in_path+f, out_path+outfile)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jpummil/Applications/alfie-master/al_align.py", line 622, in fasta2phylip
    al_index = l.split()[1]
               ~~~~~~~~~^^^
IndexError: list index out of range

PhyML is installed:
phyml --version
This is PhyML version 3.3.20220408

We get output in all of the folders except phylip:

ls -lh out/
total 21M
-rw-rw-r-- 1 jpummil jpummil  20K Jul 22 09:25 0.db.ndb
-rw-rw-r-- 1 jpummil jpummil  125 Jul 22 09:25 0.db.nhr
-rw-rw-r-- 1 jpummil jpummil  152 Jul 22 09:25 0.db.nin
-rw-rw-r-- 1 jpummil jpummil  480 Jul 22 09:25 0.db.njs
-rw-rw-r-- 1 jpummil jpummil   20 Jul 22 09:25 0.db.not
-rw-rw-r-- 1 jpummil jpummil  14M Jul 22 09:25 0.db.nsq
-rw-rw-r-- 1 jpummil jpummil  16K Jul 22 09:25 0.db.ntf
-rw-rw-r-- 1 jpummil jpummil    8 Jul 22 09:25 0.db.nto
-rw-rw-r-- 1 jpummil jpummil  333 Jul 22 09:25 0.formatdb.log
-rw-rw-r-- 1 jpummil jpummil  20K Jul 22 09:25 1.db.ndb
-rw-rw-r-- 1 jpummil jpummil  123 Jul 22 09:25 1.db.nhr
-rw-rw-r-- 1 jpummil jpummil  152 Jul 22 09:25 1.db.nin
-rw-rw-r-- 1 jpummil jpummil  477 Jul 22 09:25 1.db.njs
-rw-rw-r-- 1 jpummil jpummil   20 Jul 22 09:25 1.db.not
-rw-rw-r-- 1 jpummil jpummil 6.6M Jul 22 09:25 1.db.nsq
-rw-rw-r-- 1 jpummil jpummil  16K Jul 22 09:25 1.db.ntf
-rw-rw-r-- 1 jpummil jpummil    8 Jul 22 09:25 1.db.nto
-rw-rw-r-- 1 jpummil jpummil  333 Jul 22 09:25 1.formatdb.log
-rw-rw-r-- 1 jpummil jpummil  840 Jul 22 09:25 al_blast.sum
drwxrwxr-x 2 jpummil jpummil 4.0K Jul 22 09:25 aligned
-rw-rw-r-- 1 jpummil jpummil  16K Jul 22 09:25 blasted.fasta
-rw-rw-r-- 1 jpummil jpummil  43K Jul 22 09:25 candidate.fasta
-rw-rw-r-- 1 jpummil jpummil 3.6K Jul 22 09:25 candidate.fasta0.db.m8
-rw-rw-r-- 1 jpummil jpummil 3.2K Jul 22 09:25 candidate.fasta1.db.m8
-rw-rw-r-- 1 jpummil jpummil   42 Jul 22 09:25 distances.txt
drwxrwxr-x 2 jpummil jpummil 4.0K Jul 22 09:25 fasta
drwxrwxr-x 2 jpummil jpummil 4.0K Jul 22 09:25 nexus
drwxrwxr-x 2 jpummil jpummil 4.0K Jul 22 09:25 phylip
(Alfie) jpummil@Anubis:~/Applications/alfie-master$ ls -lh out/aligned/
total 24K
-rw-rw-r-- 1 jpummil jpummil 2.1K Jul 22 09:25 11.aln
-rw-rw-r-- 1 jpummil jpummil 2.1K Jul 22 09:25 27.aln
-rw-rw-r-- 1 jpummil jpummil 2.1K Jul 22 09:25 40.aln
-rw-rw-r-- 1 jpummil jpummil 6.1K Jul 22 09:25 all.fasta
-rw-rw-r-- 1 jpummil jpummil 2.7K Jul 22 09:25 clustal_log.txt
(Alfie) jpummil@Anubis:~/Applications/alfie-master$ ls -lh out/fasta/
total 24K
-rw-rw-r-- 1 jpummil jpummil   34 Jul 22 09:25 11.dnd
-rw-rw-r-- 1 jpummil jpummil 2.1K Jul 22 09:25 11.fasta
-rw-rw-r-- 1 jpummil jpummil   36 Jul 22 09:25 27.dnd
-rw-rw-r-- 1 jpummil jpummil 2.1K Jul 22 09:25 27.fasta
-rw-rw-r-- 1 jpummil jpummil   36 Jul 22 09:25 40.dnd
-rw-rw-r-- 1 jpummil jpummil 2.1K Jul 22 09:25 40.fasta
(Alfie) jpummil@Anubis:~/Applications/alfie-master$ ls -lh out/nexus/
total 20K
-rw-rw-r-- 1 jpummil jpummil 2.4K Jul 22 09:25 11.nexus
-rw-rw-r-- 1 jpummil jpummil 2.4K Jul 22 09:25 27.nexus
-rw-rw-r-- 1 jpummil jpummil 2.4K Jul 22 09:25 40.nexus
-rw-rw-r-- 1 jpummil jpummil 6.9K Jul 22 09:25 all.nexus
(Alfie) jpummil@Anubis:~/Applications/alfie-master$ ls -lh out/phylip/
total 0
-rw-rw-r-- 1 jpummil jpummil 0 Jul 22 09:25 all.phylip

Anything obvious? Suggestions?

**Comment by igorrcosta** [comment]
Looks like it's a formatting problem in your .aln files. Which version of clustalo do you have installed? Your clustal_log.txt file looks larger than normal. Could you show me the first line of "out/aligned/all.fasta" and "out/aligned/11.aln" files?
